name: desafio-nubank
services:
  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - nubank
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - nubank
networks:
  nubank:
    driver: bridge